
title: My Resume
url: 'http://tarinib.github.io'
baseurl: 'http://tarinib.github.io' #change it according to your repository name



# Profile information
yourname: Tarini Bhatnagar  ## put your name
title: 'Aspiring Geo+ Data Scientist'  ## your title
location: Vancouver, Canada


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
